-- 상담 내역(Consultations) 테이블 생성
CREATE TABLE public.consultations (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  type text not null,
  content text not null,
  status text default '대기중' not null,
  reply text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS (Row Level Security) 설정
ALTER TABLE public.consultations ENABLE ROW LEVEL SECURITY;

-- 퍼블릭 접근 권한: 읽기/쓰기 모두 임시로 허용 (향후 관리자용 정책 분리 권장)
CREATE POLICY "Allow public read/write for consultations" 
  ON public.consultations 
  USING (true) 
  WITH CHECK (true);
