-- 1. ai_news 테이블 생성
CREATE TABLE IF NOT EXISTS public.ai_news (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    description text,
    content text,
    image_url text,
    source_url text UNIQUE,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. 테이블 보안(RLS) 활성화
ALTER TABLE public.ai_news ENABLE ROW LEVEL SECURITY;

-- 3. 권한 정책(Policy) 추가
-- (누구나 읽을 수 있고, 크롤러봇(anon)은 글을 쓸 수 있게 설정)
CREATE POLICY "Enable read for all" ON public.ai_news FOR SELECT TO public USING (true);
CREATE POLICY "Enable insert for anon (crawler)" ON public.ai_news FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Enable all for service_role" ON public.ai_news FOR ALL TO service_role USING (true);
