-- properties 테이블 생성
CREATE TABLE public.properties (
  id bigint generated by default as identity primary key,
  title text not null,
  address text not null,
  price text not null,
  description text not null,
  type text not null,
  size text not null,
  rooms integer not null,
  baths integer not null,
  "isRecommended" boolean default false,
  "isUrgent" boolean default false,
  image text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS 정책 설정 (누구나 읽을 수 있고, 쓰기/수정/삭제는 인증된 사용자나 서비스 역할에 위임)
ALTER TABLE public.properties ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access"
  ON public.properties
  FOR SELECT
  USING (true);

CREATE POLICY "Allow insert"
  ON public.properties
  FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Allow update"
  ON public.properties
  FOR UPDATE
  USING (true);

CREATE POLICY "Allow delete"
  ON public.properties
  FOR DELETE
  USING (true);
