-- 1. ai_news 테이블 생성
CREATE TABLE IF NOT EXISTS public.ai_news (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    description text,
    content text,
    image_url text,
    source_url text UNIQUE,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. 테이블 보안(RLS) 활성화
ALTER TABLE public.ai_news ENABLE ROW LEVEL SECURITY;

-- 3. 권한 정책(Policy) 추가
-- (누구나 읽고 쓰고 수정하고 지울 수 있도록 허용)
DROP POLICY IF EXISTS "Enable read for all" ON public.ai_news;
DROP POLICY IF EXISTS "Enable insert for anon (crawler)" ON public.ai_news;
DROP POLICY IF EXISTS "Enable all for service_role" ON public.ai_news;

CREATE POLICY "Allow public read/write for ai_news" ON public.ai_news USING (true) WITH CHECK (true);
