-- 1. 중개업소 (테넌트) 테이블 - 향후 멀티테넌트 SaaS 확장을 대비
CREATE TABLE public.agencies (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  ceo_name text not null,
  phone text,
  address text,
  email text,
  notification_phone text,
  registration_number text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. 공통 코드 그룹 테이블 (기준정보 카테고리)
CREATE TABLE public.code_groups (
  id text primary key, -- 예: 'PROPERTY_TYPE', 'TRANSACTION_TYPE'
  name text not null,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. 상세 공통 코드 테이블 (실제 기준정보 데이터)
CREATE TABLE public.common_codes (
  id uuid default gen_random_uuid() primary key,
  group_id text references public.code_groups(id) on delete cascade,
  code_value text not null, -- 예: 'APT', 'SALE'
  code_name text not null, -- 예: '아파트', '매매'
  sort_order integer default 0,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  UNIQUE(group_id, code_value)
);

-- 4. 플랫폼용 매물 테이블 고도화 버젼 (properties_v2)
CREATE TABLE public.properties_v2 (
  id bigint generated by default as identity primary key,
  agency_id uuid references public.agencies(id),
  title text not null,
  address text not null,
  
  property_type_code text not null, -- common_codes 의 code_value
  transaction_type_code text not null, -- common_codes 의 code_value
  
  price_main bigint not null, -- 매매가 또는 보증금 (단위: 만원)
  price_monthly bigint default 0, -- 월세 (단위: 만원)
  
  description text not null,
  size text not null,
  rooms integer not null,
  baths integer not null,
  "isRecommended" boolean default false,
  "isUrgent" boolean default false,
  image text not null,
  asil_id text,
  naver_id text,
  status text default '광고중',
  verification_type text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ====================================================
-- 기초(Seed) 데이터 삽입
-- ====================================================

-- 테스트용 리더스가든 중개업소 생성
INSERT INTO public.agencies (id, name, ceo_name, phone, address, email, notification_phone, registration_number) 
VALUES ('11111111-1111-1111-1111-111111111111', '리더스가든 부동산', '유현휘', '010-4630-0363', '경기도 양주시 옥정로', 'jhpa670211@gmail.com', '010-4630-0363', '123-45-67890')
ON CONFLICT (id) DO NOTHING;

-- 기준정보 그룹 세팅
INSERT INTO public.code_groups (id, name) VALUES 
('PROPERTY_TYPE', '매물 종류'),
('TRANSACTION_TYPE', '거래 방식')
ON CONFLICT (id) DO NOTHING;

-- 기본 기준정보 세팅
INSERT INTO public.common_codes (group_id, code_value, code_name, sort_order) VALUES 
('PROPERTY_TYPE', 'APT', '아파트', 1),
('PROPERTY_TYPE', 'VILLA', '연립/다세대', 2),
('PROPERTY_TYPE', 'COMMERCIAL', '상가/사무실', 3),
('PROPERTY_TYPE', 'OFFICETEL', '오피스텔', 4),
('PROPERTY_TYPE', 'ONE_ROOM', '원룸/투룸', 5),

('TRANSACTION_TYPE', 'SALE', '매매', 1),
('TRANSACTION_TYPE', 'JEONSE', '전세', 2),
('TRANSACTION_TYPE', 'MONTHLY', '월세', 3),
('TRANSACTION_TYPE', 'SHORT_TERM', '단기임대', 4)
ON CONFLICT (group_id, code_value) DO NOTHING;

-- ====================================================
-- RLS (Row Level Security) 설정 - 임시로 모두 허용
-- 실제 서비스 오픈 시 Auth 유저 기반으로 제한 필요
-- ====================================================
ALTER TABLE public.agencies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.code_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.common_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.properties_v2 ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read/write" ON public.agencies USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write" ON public.code_groups USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write" ON public.common_codes USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write" ON public.properties_v2 USING (true) WITH CHECK (true);
