export const properties = [
  {
    id: 1,
    title: "리더스가든 부동산 강력 추천 매물",
    address: "경기도 양주시 옥정동로",
    price: "매매 5억 2,000",
    description: "남향, 올수리 완료, 즉시입주 가능",
    type: "아파트",
    size: "84㎡",
    rooms: 3,
    baths: 2,
    isRecommended: true,
    isUrgent: false,
    image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: 2,
    title: "옥정신도시 초역세권 상가",
    address: "경기도 양주시 옥정동",
    price: "보증금 5,000 / 월 300",
    description: "유동인구 최다, 권리금 없음",
    type: "상가",
    size: "50㎡",
    rooms: 1,
    baths: 1,
    isRecommended: false,
    isUrgent: true,
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: 3,
    title: "신축 풀옵션 원룸",
    address: "경기도 양주시 옥정로",
    price: "전세 1억 2,000",
    description: "엘리베이터 있음, 주차 가능, 조용한 주택가",
    type: "원룸",
    size: "25㎡",
    rooms: 1,
    baths: 1,
    isRecommended: true,
    isUrgent: true,
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: 4,
    title: "전망 좋은 고층 아파트",
    address: "경기도 양주시 옥정동로",
    price: "매매 6억 5,000",
    description: "호수공원 뷰, 로얄층, 관리 상태 최상",
    type: "아파트",
    size: "105㎡",
    rooms: 4,
    baths: 2,
    isRecommended: false,
    isUrgent: false,
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: 5,
    title: "투자용 다가구 주택",
    address: "경기도 양주시 덕정동",
    price: "매매 8억",
    description: "수익률 6%, 만실, 리모델링 완료",
    type: "주택",
    size: "300㎡",
    rooms: 8,
    baths: 8,
    isRecommended: true,
    isUrgent: false,
    image: "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: 6,
    title: "채광 좋은 남향 투룸",
    address: "경기도 양주시 옥정동",
    price: "보증금 2,000 / 월 80",
    description: "신혼부부 추천, 풀옵션, 애완동물 협의",
    type: "투룸",
    size: "45㎡",
    rooms: 2,
    baths: 1,
    isRecommended: false,
    isUrgent: true,
    image: "https://images.unsplash.com/photo-1502672260266-1c1de2d9d0cb?auto=format&fit=crop&w=800&q=80"
  }
];
